query DatabaseDependencies {
  databases {
    name
    connectionType
    ... on File {
      filePath
    }
    ... on DatabaseServer {
      hostName
    }
    ... on CloudFile {
      fileId
    }
    downstreamWorkbooks {
      luid
    }
    downstreamDatasources {
      luid
    }
  }
}