tables:
    - name: content
      fields:
        - name: content_type
          type: text
        - name: content_id
          type: text
        - name: name
          type: text
        - name: owner
          type: text
        - name: project
          type: text
        - name: description
          type: text
      query: content.gql

    - name: tags
      fields:
        - name: content_id 
          type: text
        - name: tag
          type: text
      query: tags.gql

    - name: content_dependencies
      fields:
        - name: upstream_content_id
          type: text
        - name: downstream_content_id
          type: text
      query: content_dependencies.gql

    - name: database_dependencies
      fields:
        - name: upstream_content_id
          type: text
        - name: location
          type: text
        - name: database
          type: text
        - name: type
          type: text
      query: database_dependencies.gql

    